### ISSUE TITLE
can't build success

### ISSUE THREAD

**Issue by liu-yuhuan** [niftylettuce/react-native-loading-spinner-overlay#1]
got something wrong，can't build success

my react native version is 0.17.0

tatsuo769/Library/Developer/Xcode/DerivedData/sushi_project-dcfcgmcxmrxxqtepwgrfknmuzvua/Build/Products/Debug-iphonesimulator/sushi_project.app/main.jsbundle --assets-dest /Users/tatsuo769/Library/Developer/Xcode/DerivedData/sushi_project-dcfcgmcxmrxxqtepwgrfknmuzvua/Build/Products/Debug-iphonesimulator/sushi_project.app
bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module autobind-decorator from /Users/tatsuo769/Sites/sushi_project/node_modules/react-native-loading-spinner-overlay/lib/index.js: Invalid directory /Users/node_modules/autobind-decorator
    at ResolutionRequest.js:351:15
    at tryCallOne (/Users/tatsuo769/Sites/sushi_project/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/tatsuo769/Sites/sushi_project/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/tatsuo769/Sites/sushi_project/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
See logs /var/folders/l1/wd3t_vcj4d9593_8_rpgsvww0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:78:13)
    at BunserBuf.emit (events.js:170:7)
    at BunserBuf.process (/Users/tatsuo769/Sites/sushi_project/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/tatsuo769/Sites/sushi_project/node_modules/react-native/node_modules/bser/index.js:244:12
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
Command /bin/sh failed with exit code 1

**Comment by enu-kuro** [comment]
That's because "autobind-decorator" isn't installed. I fixed and sent pull request.

**Comment by niftylettuce** [comment]
thank you!!!!  publishing new version to npm now

**Comment by niftylettuce** [comment]
`v0.0.6` on NPM, thanks @enu-kuro
